theme: jekyll-theme-cayman

# needed for CI builds:
exclude: [vendor]

# Site settings
title: Wasiur R. KhudaBukhsh
description: 
email: khudabukhsh.2@osu.edu
url: "https://wasiur.github.io/" # the base hostname & protocol for your site
