theme: jekyll-theme-cayman

# needed for CI builds:
exclude: [vendor]

# Site settings
title: Wasiur R. KhudaBukhsh
description: 
email: wasiur.khudabukhsh@nottingham.ac.uk
url: "https://wasiur.github.io/" # the base hostname & protocol for your site
